### ISSUE TITLE
Create Problem instance from code

### ISSUE THREAD

**Issue by MFaisalZaki** [ztangent/PDDL.jl#2]
Hello,

I was wondering if we can create problem instances from code rather than loading from a file?

Best,
Mustafa

**Comment by ztangent** [comment]
Hi! Currently the easiest way to do things is to write a PDDL file or string. Alternatively, you can construct an initial state by specifying the list of initial facts and object type declarations, e.g. for Blocksworld:
```julia
state = State(@pddl("(on-table a)", "(on b a)", "(on-table c)"),  @pddl("(block a)", "(block b)", "(block c)"))
```
You can specify goals using `@pddl` or `@julog`, depending on which syntax you prefer, e.g.
```julia
# Stack A on B on C
goals = @pddl("(on a b)", "(on b c)") # PDDL syntax
goals = @julog [on(a, b), on(b, c)] # Prolog-style syntax
```
